name: Release

on:
  push:
    branches:
      - master
      - alpha
      - beta
      - next
jobs:
  build:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: npm i
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Test
        run: |
          npm test
          npm run readme:coverage
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Deploy
        run: npm run semantic-release -- --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
